In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [7]:
A = np.random.randn(10)
A

array([ 1.83184541, -1.40117843, -0.54163107, -0.01479056,  0.1437921 ,
        0.20423508,  1.33124739, -1.94669784,  0.73526277, -0.23878996])

In [8]:
B = np.random.randn(10)
B

array([-1.14647613, -0.26133668,  0.25599909, -1.3017999 ,  1.07041451,
       -0.44098437, -0.13262807,  1.19030676, -0.19717947,  0.1645638 ])

In [9]:
np.add(A,B)

array([ 0.68536927, -1.66251511, -0.28563197, -1.31659046,  1.21420661,
       -0.23674928,  1.19861932, -0.75639108,  0.5380833 , -0.07422616])

In [10]:
np.maximum(A,B)

array([ 1.83184541, -0.26133668,  0.25599909, -0.01479056,  1.07041451,
        0.20423508,  1.33124739,  1.19030676,  0.73526277,  0.1645638 ])

# Docs:

In [11]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True