In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
np.save('my_array',arr) #Saving array on disk in binary format (file extension .npy)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [9]:
arr2 = np.random.randn(5)
arr2

array([-0.15850296, -0.86634913, -1.02249695,  0.65738763, -0.54457427])

In [10]:
np.savez('two_arr.npz',x=arr,y=arr2) #Saving multiple arrays into a zip file

In [11]:
archive_arr = np.load('two_arr.npz') #Now loading multiple arrays
archive_arr['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
archive_arr['y']

array([-0.15850296, -0.86634913, -1.02249695,  0.65738763, -0.54457427])

In [21]:
arr3 = np.array([[1,2,3],[4,5,6]])
np.savetxt("my_test.txt",arr3,delimiter=',')

In [22]:
arr3_l = np.loadtxt('my_test.txt',delimiter=',')
arr3_l

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

# my_test.txt
### 1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
### 4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00