In [14]:
import numpy as np

In [15]:
my_lst1 = [1,2,3,4]

In [16]:
my_arr1 = np.array(my_lst1)

In [17]:
my_arr1

array([1, 2, 3, 4])

In [18]:
my_lst2 = [11,12,13,14]

In [19]:
my_lsts = [my_lst1, my_lst2]

In [20]:
my_arrs = np.array(my_lsts)

In [21]:
my_arrs

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [22]:
my_arrs.shape()

TypeError: 'tuple' object is not callable

In [23]:
my_arrs.shape # No. of rows, No. of Columns

(2L, 4L)

In [24]:
my_arrs.dtype

dtype('int32')

In [25]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [26]:
my_zeros = np.zeros(5)

In [27]:
my_zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [28]:
my_ones = np.ones(5)

In [29]:
my_ones

array([ 1.,  1.,  1.,  1.,  1.])

In [30]:
my_ones = np.ones(5,5)

TypeError: data type not understood

In [31]:
my_ones = np.ones((5,5))

In [32]:
my_ones

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [33]:
my_ones.dtype

dtype('float64')

In [34]:
np.empty(5) #Same as np.zeros

array([ 0.,  0.,  0.,  0.,  0.])

In [35]:
np.empty((3,6))

array([[  3.54266491e-316,   3.53183064e-316,   3.49732114e-316,
          3.22271037e-316,   3.45059558e-316,   3.18115945e-316],
       [  1.97479264e-316,   3.20092879e-317,   3.20097227e-317,
          3.20101575e-317,   3.20105922e-317,   2.83637435e-316],
       [  8.34454050e-308,   1.11261027e-306,   1.15706896e-306,
          1.33512173e-306,   3.49698923e-317,   0.00000000e+000]])

In [36]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [37]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(10, 100 ,15) #(start,stop,step)

array([10, 25, 40, 55, 70, 85])

In [39]:
np.arange(100, 10, -15)

array([100,  85,  70,  55,  40,  25])

###### In previous the stop is not included in the result similar to Python extremities.