In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:4] = 50

In [11]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:4]
print slice_of_arr
print arr
for i in range(4):
    slice_of_arr[i] = i
print slice_of_arr
print arr

[50 50 50 50]
[50 50 50 50  4  5  6  7  8  9 10]
[0 1 2 3]
[ 0  1  2  3  4  5  6  7  8  9 10]


###### slice_of_array works as a pointer to the mentioned elements of the array instead of a copy.

### Array copy:

In [14]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 2D Arrays

In [15]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr_2d[1]

array([5, 6, 7, 8])

In [17]:
arr_2d[1][2]

7

In [18]:
arr_2d[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [19]:
arr_2d[2]

array([ 9, 10, 11, 12])

In [20]:
arr_2d[2,:]

array([ 9, 10, 11, 12])

In [21]:
arr2d = np.zeros(3,5)

TypeError: data type not understood

In [22]:
arr2d = np.zeros((3,5))

In [23]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [27]:
arr2d_length = arr2d.shape[0] #No. of rows
arr2d_length

3L

In [28]:
arr2d_length2 = arr2d.shape[1] #No. of columns
arr2d_length2

5L

In [30]:
for i in range(arr2d_length):
               arr2d[i] = i*i
arr2d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.]])

In [31]:
arr2d2 = np.eye(5)
arr2d2

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [32]:
arr2d2 = arr2d2 + arr2d2
arr2d2

array([[ 2.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [33]:
arr2d2[[2,4,0,1,3]] #Fancy indexing

array([[ 0.,  0.,  2.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.],
       [ 2.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  0.]])